# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bf306ecabab9374113ad62b9e8829780515716a72653d771a958499071517d77dda6fba9de69d947ba22eb305d7effd6b19af1ce89a691cab4a4b718b714fab

test:
  secret_key_base: 342b9d3b5986432e624842c29f8c53e473794e8ef5962340184e9a0642deed6c7d39f44492050c6a6c7779fe9e14236d3ddcc4dd35cdd9e396c7ba17b9a6d842

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
